#!/usr/bin/env python
import sys
import re



message = open(sys.argv[1])
commitMessage = message.read().strip()
regex = re.compile(r"DR[1-9]{5}|DR[1-9]{6}|DR-[1-9]{5}|DR-[1-9]{6}")
if re.search(regex, commitMessage) is None:
	print('''Your commit message is not formatted correctly. Use DR options as shown below.
	
	DRxxxxx OR DRxxxxxx OR DR-xxxxxx OR DR-xxxxx
	where 'x' can be 1-9 only
	Exiting now, try again with correct DR format.''')
  	sys.exit(1)
else:
	sys.exit(0)




